#include "main.h"

void init_max_spi1(void){
	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
	RCC->APB2ENR |= RCC_APB2ENR_SPI1EN;
	
	//GPIO SETUP PA5 & PA7 AS AF PA3 AS GPIO LOAD LINE
	GPIOA->CRL |= GPIO_CRL_CNF5_1;
	GPIOA->CRL &= ~GPIO_CRL_CNF5_0;
	GPIOA->CRL |= GPIO_CRL_MODE5;
	
	GPIOA->CRL |= GPIO_CRL_CNF7_1;
	GPIOA->CRL &= ~GPIO_CRL_CNF7_0;
	GPIOA->CRL |= GPIO_CRL_MODE7;
	
	GPIOA->CRL &= ~GPIO_CRL_CNF3;
	GPIOA->CRL |= GPIO_CRL_MODE3_1;
	GPIOA->BSRR |= GPIO_BSRR_BS3;
	
	
	//CONFIGURE SPI1 SIMPLEX MASTER MODE
	SPI1->CR1 |= SPI_CR1_BIDIMODE | SPI_CR1_BIDIOE;
	SPI1->CR1 |= SPI_CR1_MSTR | SPI_CR1_BR_0 | SPI_CR1_BR_1;
	SPI1->CR2 |= SPI_CR2_SSOE;
	SPI1->CR1 |= SPI_CR1_SPE;
	
}

void send_spi1_max(uint8_t address, uint8_t data){
	GPIOA->BSRR |= GPIO_BSRR_BR3;
	SPI1->DR = address;
	while((SPI1->SR & SPI_SR_TXE) != SPI_SR_TXE);
	SPI1->DR = data;
	while((SPI1->SR & SPI_SR_TXE) != SPI_SR_TXE);
	GPIOA->BSRR |= GPIO_BSRR_BS3;
}